version: '{build}'

image:
- Visual Studio 2022
- Ubuntu2004

environment:
  # vm-tests compatibility flags: VM_CONFIG_COMPAT_WHV_DEBUG
  VM_TESTS_COMPAT_FLAGS: 0x80000000

  matrix:
  - Configuration: Debug
  - Configuration: Release

install:
- ps: |
    git submodule update --init --recursive
    if ($isWindows) {
        Enable-WindowsOptionalFeature -Online -FeatureName HypervisorPlatform -All
        wsl sudo apt-get -qy update
        wsl sudo apt-get -qy install g++ gdb make ninja-build rsync zip
    } elseif ($isLinux) {
        sudo chmod o+rw /dev/kvm
    }

build_script:
- ps: |
    if ($isWindows) {
        python tools/build.py $env:Configuration
    } elseif ($isLinux) {
        python3 tools/build.py $env:Configuration
    }

test_script:
- ps: |
    if ($isWindows) {
        & build/VStudio/build/$env:Configuration/vm-tests
    } elseif ($isLinux) {
        & build/Linux/build/$env:Configuration/vm-tests
    }
