version: '{build}'

image: Visual Studio 2022

environment:
  # vm-tests compatibility flags: VM_CONFIG_COMPAT_WHV_DEBUG
  VM_TESTS_COMPAT_FLAGS: 0x80000000

  matrix:
  - Configuration: Debug
  - Configuration: Release

install:
- ps: Enable-WindowsOptionalFeature -Online -FeatureName HypervisorPlatform -All
- wsl sudo apt-get -qy update
- wsl sudo apt-get -qy install g++ gdb make ninja-build rsync zip

build_script:
- python tools\build.py %Configuration%

test_script:
- build\VStudio\build\%Configuration%\vm-tests.exe
